const CATALOG = [
  {
    id: "nike1",
    name: "Nike SB Dunk Low Colourful",
    price: 2399,
    extra: 0,
    img: "./products/nike-dunk-sb-low-cf.jpg",
    sizes: [6, 7, 8, 9],
  },
  {
    id: "nike2",
    name: "Nike SB Dunk Low x Otomo Katsuhiro",
    price: 2399,
    extra: 0,
    img: "./products/nike-sb-dunk-low-x-otomo-katsuhiro.jpg",
    sizes: [6, 7, 8, 9, 10],
  },
  {
    id: "nike3",
    name: "Nike SB Dunk Low Greyish",
    price: 2399,
    extra: 0,
    img: "./products/nike-sb-dunk-low-greyish.jpg",
    sizes: [6, 7, 8, 9, 10],
  },
  {
    id: "nike4",
    name: "Nike SB Dunk Low x Otomo Katsuhiro",
    price: 2399,
    extra: 0,
    img: "./products/nike-sb-dunk-otomo.jpg",
    sizes: [6, 7, 8, 9, 10],
  },
  {
    id: "nike5",
    name: "Nike SB Dunk Low Custom 2025",
    price: 2399,
    extra: 0,
    img: "./products/nike-sb-dunk-custom-2025.jpg",
    sizes: [6, 7, 8, 9, 10],
  },
  {
    id: "nike6",
    name: "Nike SB Dunk Low Born x Raised",
    price: 2399,
    extra: 0,
    img: "./products/nike-sb-dunk-low-born-x-raised.jpg",
    sizes: [6, 7, 8, 9, 10],
  },
  {
    id: "nike7",
    name: "Nike SB Dunk Low Stussy Grey Orange",
    price: 2399,
    extra: 0,
    img: "./products/nike-sb-dunk-stussy-grey-orange.jpg",
    sizes: [6, 7, 8, 9, 10],
  },
  {
    id: "nike8",
    name: "Nike SB Dunk Low Year of the Snake",
    price: 2399,
    extra: 0,
    img: "./products/nike-sb-dunk-year-of-the-snake.jpg",
    sizes: [6, 7, 8, 9, 10],
  },
  {
    id: "nike9",
    name: "Jordan Jumpman Jack TP Travis Scott Dark Mocha",
    price: 2699,
    extra: 0,
    img: "./products/jordan-jumpman-jack-tp-travis-scott-dark-mocha.jpg",
    sizes: [6, 7, 8, 9, 10],
  },
  {
    id: "nike10",
    name: "Nike Airforce Big Bank Chunky",
    price: 2599,
    extra: 0,
    img: "./products/nike-airforce-big-bank-chunky.jpg",
    sizes: [6, 7, 8, 9, 10],
  },
];
